exclude: ^.*(.min.js|.min.css)$
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
        args: ["--unsafe"] # because of tags in mkdocs.yml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files"]
  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-black>=0.1.1
        args: ["--max-line-length=88", "--ignore=E20,W503,E704"] # black compatible
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        files: \.(css|less|md|json|sql)$
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.2.0
    hooks:
      - id: eslint
        additional_dependencies:
          - eslint@8.14.0
          - eslint-config-google@0.14.0
          - eslint-plugin-jsdoc@39.3.3
          - eslint-config-standard@17.0.0
        args: ["--fix"]
