site_name: "" # use title from README
repo_url: https://github.com/wingechr/datatools

# Configuration
theme:
  name: material
  locale: en
  features:
    #- navigation.tabs
    #- navigation.tabs.sticky
    #- navigation.sections
    #- navigation.indexes
    #- navigation.path
    #- navigation.tracking
    #- navigation.footer
    #- navigation.top
    #- toc.follow
    #- search.suggest
    #- search.share

# Extensions
markdown_extensions:
  #- admonition
  #- attr_list
  #- def_list
  #- md_in_html
  #- pymdownx.details
  - pymdownx.superfences # code highlight
  - pymdownx.snippets # include README

plugins:
  #- mkdocs-jupyter:
  #    execute: true
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: false
            show_root_heading: true
            show_root_full_path: true
            docstring_style: numpy
  - search:
      lang: en
