site_name: DataDisAggregation

# Configuration
theme:
  name: material
  locale: en
  features:
    #- navigation.tabs
    #- navigation.tabs.sticky
    #- navigation.sections
    #- navigation.indexes
    #- navigation.path
    #- navigation.tracking
    #- navigation.footer
    #- navigation.top
    #- toc.follow
    #- search.suggest
    #- search.share

# Extensions
markdown_extensions:
  #- admonition
  #- attr_list
  #- def_list
  #- md_in_html
  #- pymdownx.details
  #- pymdownx.superfences

plugins:
  #- mkdocs-jupyter:
  #    execute: false
  - mkdocstrings:
      handlers:
          python:
            options:
              show_source: false
  - search:
      lang: en
