[project]
name = "wingechr-datatools"
version = "0.13.1"
description = "TODO"
readme = "README.md"
requires-python = ">=3.9,<3.14"
authors = [
  { name="Christian Winger", email="c@wingechr.de" }
]
dependencies = [
    "appdirs>=1.4.4",
    "chardet>=5.2.0",
    "jsonpath-ng>=1.7.0",
    "pandas>=2",
    "requests>=2",
    "sqlalchemy>=2.0.41",
    "sqlparse>=0.5.3",
    "tzlocal>=5.3.1",
    "unidecode>=1.4.0",
]
[project.urls]
[tool.setuptools]
packages = ["datatools"]

[dependency-groups]
dev = [
    "bumpversion>=0.6.0",
    "pre-commit>=4.2.0",
    "tox>=4",
    "tox-uv>=1.26.1",
    "uv>=0.7.19",
    "vulture>=2.14",
]
docs = [
    "mdx-truly-sane-lists>=1.3",
    "mistune~=2.0",
    "mkdocs>=1.6",
    "mkdocs-material", # NOTE problems installing in windows
    "mkdocstrings-python>=1.16",
    "pymdown-extensions>=10.16",
]
