[project]
name = "datatools"
version = "0.12.0"
description = "TODO"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "jsonpath-ng>=1.7.0",
]

[dependency-groups]
dev = [
    "bumpversion>=0.6.0",
    "pre-commit>=3.5.0",
    "tox>=4",
    "tox-uv>=1.13.1",
    "uv>=0.7.18",
]
