name: docs

on:
  push:
    branches:
      - main
      - dev

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - run: pip install uv
      - run: uv run --group=docs mkdocs gh-deploy --force
