name: docs

on:
  push:
    branches:
      - main

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - run: |
          pip install uv
          uv venv install --no-default --group docs
      - run: |
          uv venv run mkdocs gh-deploy --force
