name: pages
on:
  push:
    branches:
      - main
permissions:
  contents: write
  id-token: write
  pages: write
jobs:
  pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm ci && npm run build
      - uses: actions/upload-pages-artifact@v1
        with:
          path: _pages
      - uses: actions/deploy-pages@v2
